# ML MATH PREREQUISITES
**Bài Tập Tự Học & Luyện Tập:** Linear Algebra • Calculus • Probability & Statistics

Notebook này được chia làm 4 phần chính tương ứng với các kiến thức nền tảng trong Toán học áp dụng thuật toán Machine Learning.

In [2]:
# Import các thư viện toán học cần thiết
import numpy as np
from scipy.stats import norm

## PHẦN 1 — LINEAR ALGEBRA
Mỗi quan sát (data point) được biểu diễn là một vector. Thao tác trên vector và ma trận là bản chất cốt lõi để thực hiện tính toán song song trong ML.

In [3]:
# --- Bài 1.1: Scalars và Vectors ---
# Định nghĩa vector các căn nhà: [diện_tích, số_phòng, tuổi_nhà, số_tầng]
house_A = np.array([85, 2, 5, 3])
house_B = np.array([120, 3, 10, 7])
house_C = np.array([200, 4, 2, 1])
print(f"Shape của vector House A: {house_A.shape}")

# --- Bài 1.2: Vector Addition ---
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])
uv_sum = u + v
print(f"Tổng u+v: {uv_sum}")

pred_model1 = np.array([0.2, 0.7, 0.5, 0.9])
pred_model2 = np.array([0.3, 0.6, 0.4, 0.8])
ensemble_avg = (pred_model1 + pred_model2) / 2
print(f"Ensemble Average: {ensemble_avg}") # Vị trí 2 & 4 cả 2 model đồng thuận khả năng cao

# --- Bài 1.3: Scalar Multiplication & GD Step ---
W_old = np.array([0.5, -0.3, 0.8])
gradient = np.array([0.1, -0.2, 0.05])
alpha = 0.01
W_new = W_old - alpha * gradient
print(f"Cập nhật Gradient: {W_new}")

# --- Bài 1.4: Dot Product ---
dot_uv = np.dot(u, v) 
print(f"Dot product u.v: {dot_uv}")

x = np.array([320, 8.5, 1.0])
w = np.array([0.002, 0.05, 0.03])
b = -0.5
y_pred = np.dot(w, x) + b
print(f"Linear_prediction: {y_pred:.4f}")

# --- Bài 1.5: Vector Norms & Regularization ---
vec = np.array([1, 2, 3, 4, 5])
print(f"L2 Norm: {np.linalg.norm(vec):.4f}")
print(f"L1 Norm: {np.linalg.norm(vec, ord=1)}")

a, b = np.array([1, 2, 3]), np.array([4, 5, 6])
cosine_sim = np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))
print(f"Cosine Similarity: {cosine_sim:.4f}")

# --- Bài 1.6 & 1.7: Matrix Operations ---
X = np.array([[85, 8.2, 2], [92, 9.0, 3], [70, 7.5, 1], [88, 8.7, 4]])
W_mat = np.array([[0.4, 0.1], [0.3, 0.5], [0.2, 0.3]])

Z = X @ W_mat
print(f"\nShape X@W: {Z.shape}") # (4,3) @ (3,2) = (4,2)

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [1, 2, 3]])
print(f"Hadamard Product (A * B):\n{A * B}")

M = np.array([[2.0, 1.0], [5.0, 3.0]])
M_inv = np.linalg.inv(M)
print(f"M_inv @ M:\n{np.round(M_inv @ M, 8)}") # Ma trận đơn vị

Shape của vector House A: (4,)
Tổng u+v: [5 7 9]
Ensemble Average: [0.25 0.65 0.45 0.85]
Cập nhật Gradient: [ 0.499  -0.298   0.7995]
Dot product u.v: 32
Linear_prediction: 0.5950
L2 Norm: 7.4162
L1 Norm: 15.0
Cosine Similarity: 0.9746

Shape X@W: (4, 2)
Hadamard Product (A * B):
[[ 7 16 27]
 [ 4 10 18]]
M_inv @ M:
[[1. 0.]
 [0. 1.]]


### Trả lời lý thuyết phần Linear Algebra:
*   **Vector dimension:** Thêm tính năng khoảng cách, kích thước vector sẽ thuộc không gian **ℝ⁵**. Learning rate $\alpha$ là scalar (hằng số không chiều) để scale toàn bộ bước bước nhảy đi một tỷ lệ chung.
*   **Ensemble learning:** Tính trung bình (average) dự đoán của các mô hình sẽ giúp giảm variance, hạn chế overfitting so với 1 model đơn lẻ vì các sai số nhỏ có thể triệt tiêu cho nhau.
*   **Trừ Gradient:** Gradient của hàm Loss biểu thị hướng giúp làm biến thiên Loss theo chiều *Tăng* lớn nhất. Vì vậy, để tối ưu Model (Tức là làm *Giảm* Loss đi), ta phải nhảy theo chiều ngược lại (phép Trừ).
*   **Lasso (L1):** L1 sử dụng trị tuyệt đối nên đạo hàm của nó độc lập với kích thước weight. Điều này kéo mạnh tay các hệ số rác cực kỳ nhỏ về đúng $0$ (tạo sparsity - lọc biến). L2 phạt theo bình phương nên các hệ số nhỏ đạo hàm cũng sẽ nhỏ lại, khó xuống chặt 0.
*   **Matrix Mult ($X \times W$):** Trong Neural Networks, hoạt động này chính là nhân weights trong trạng thái fully connected / Linear Layer.

## PHẦN 2 — CALCULUS
Tập trung vào tối ưu hóa hàm số, tìm điểm cực tiểu bằng kỹ thuật thay đổi trọng số theo đạo hàm.

In [4]:
# --- Tính đạo hàm và Gradient Descent Tay theo Bài 2.1 & 2.3 ---
# Tìm dL/dW với MSE: MSE = (y - ŷ)^2
# Cho w=0.5, x=2.0, y=1.0. 
w, x, y = 0.5, 2.0, 1.0
y_hat = w * x       # 1.0
error = y - y_hat   # 0.0
# Đạo hàm của MSE theo hệ số w: dL/dw = -2 * x * error
dL_dw = -2 * x * error # = 0.0 -> Trọng số đã tối ưu tại điểm này

# 2 Tham số: MSE = (y - (w1*x1 + w2*x2))^2. Với y=1, x=[2,3], w=[0.3,0.2]
x1, x2, w1, w2 = 2.0, 3.0, 0.3, 0.2
y_hat2 = w1*x1 + w2*x2  # = 1.2
err2 = 1.0 - y_hat2     # = -0.2

dL_dw1 = -2 * x1 * err2 # = 0.8
dL_dw2 = -2 * x2 * err2 # = 1.2
print(f"dL_dw1: {dL_dw1:.2f}, dL_dw2: {dL_dw2:.2f}")

# --- Gradient Descent bước ngắn (bài 2.3) ---
# f(x, y) = x^2 + y^2 => grad = [2x, 2y]
p = np.array([3.0, 4.0])
alpha = 0.1
print("\nCác bước Gradient Descent:")
for i in range(6):
    print(f"Bước {i}: Điểm {np.round(p,4)}, Gradient: {np.round(2*p, 4)}")
    p = p - alpha * (2 * p) # Cập nhật điểm x, y

dL_dw1: 0.80, dL_dw2: 1.20

Các bước Gradient Descent:
Bước 0: Điểm [3. 4.], Gradient: [6. 8.]
Bước 1: Điểm [2.4 3.2], Gradient: [4.8 6.4]
Bước 2: Điểm [1.92 2.56], Gradient: [3.84 5.12]
Bước 3: Điểm [1.536 2.048], Gradient: [3.072 4.096]
Bước 4: Điểm [1.2288 1.6384], Gradient: [2.4576 3.2768]
Bước 5: Điểm [0.983  1.3107], Gradient: [1.9661 2.6214]


### Trả lời lý thuyết phần Calculus:
*   **Partial Derivatives:** Khi tính partial đạo hàm theo một biến, ta treat biến còn lại như hằng số. Đạo hàm theo $w_2$ lớn hơn do đặc trưng $x_2$ có magnitude lớn hơn, chi phối loss output mạnh hơn $x_1$. 
*   **Gradient Descent:** Lặp lại dần Gradient sẽ để hội tụ về điểm tọa độ `(0.0, 0.0)`. Đây là vị trí cực tiểu vì Vector Gradient tại đây là `[0, 0]`.
*   **Chain Rule:** Áp dụng liên hoàn các đạo hàm thành phần. Vấn đề "Dying ReLU": Tại ReLU(z) với $z \lt 0$, local gradient ngay lập tức $= 0$. Nên theo quy luật chuỗi (chain rule nhân dần các thành phần), Global gradient cho trọng số cũng $\to 0$. Model sẽ không học tiếp được hệ số này ở các bước sau tiếp theo.

## PHẦN 3 — PROBABILITY & STATISTICS
Tính kỳ vọng, phương sai, xác suất Bayes làm nền tảng cho nhiều Model (Classification, GMM, Naive Bayes).

In [5]:
scores = np.array([72, 85, 90, 68, 78, 95, 60, 82, 77, 88])
print(f"Mean (μ): {np.mean(scores)}")
print(f"Median: {np.median(scores)}")
print(f"Standard Dev (σ): {np.std(scores):.2f}\n")

class_A = np.array([70, 75, 72, 78, 73])
class_B = np.array([50, 95, 60, 90, 55])
print(f"Std class A: {np.std(class_A):.2f}")
print(f"Std class B: {np.std(class_B):.2f}") # B lệch mạnh hơn

# Normal Distribution:
# N(μ=70, σ=12)
print(f"\nP(điểm > 80): {norm.sf(80, 70, 12):.4f}")
print(f"P(điểm < 50): {norm.cdf(50, 70, 12):.4f}")
print(f"Top 10% cutoff: {norm.ppf(0.9, 70, 12):.2f}")

# Expectation & Covariance
GRE = np.array([310, 325, 295, 335, 305])
Admit = np.array([0.65, 0.80, 0.52, 0.90, 0.68])
cov_matrix = np.cov(GRE, Admit, ddof=0)
print(f"Covariance Matrix:\n {cov_matrix}")

rho = cov_matrix[0,1] / (np.std(GRE) * np.std(Admit))
print(f"Correlation (ρ): {rho:.4f}")

Mean (μ): 79.5
Median: 80.0
Standard Dev (σ): 10.18

Std class A: 2.73
Std class B: 18.71

P(điểm > 80): 0.2023
P(điểm < 50): 0.0478
Top 10% cutoff: 85.38
Covariance Matrix:
 [[2.040e+02 1.820e+00]
 [1.820e+00 1.696e-02]]
Correlation (ρ): 0.9785


### Trả lời lý thuyết phần Prob & Stats:
*   **Descriptive:** Class B "nguy hiểm" hơn cho Model vì phương sai (variance) quá lớn. Mô hình khi train trên class này sẽ dễ bị underfit/overfit do phân bổ không đại diện cho số đông.
*   **Bayes Classifier:** $P(`tuyệt`) = 0.7 \times 0.6 + 0.1 \times 0.4 = 0.46$. Áp dụng Bayes: $P($Pos $\mid \text{tuyệt}) = \frac{0.7 \times 0.6}{0.46} \approx 0.913$. Xác suất lớn hơn $> 0.5$ nên ta phân loại là đánh giá POSITIVE. Nó được gọi là **Naive** (ngây thơ) vì đưa ra giả định rằng việc xuất hiện của các "Feature" (hay các "Words") này hoàn toàn có tính độc lập lẫn nhau rạch ròi.
*   **Correlation:** Correlation cao đồng biến ($\rho > 0.5$) chỉ mô tả một quan hệ đồng diễn biến hình học, chứ **KHÔNG** chứng minh quan hệ nhân quả. Tuy nhiên trong ML, GRE sẽ vẫn là một Feature cực mạnh cho mô hình nhận dự đoán.

## BÀI TỔNG HỢP — Logistic Regression Từ Đầu
Cài đặt Log-Regression với cơ chế Binary Cross Entropy, vận dụng thuần NumPy dựa vào các đạo hàm toán học phía trên.

In [7]:
np.random.seed(42)

# Khởi tạo data giả lập
X_train = np.random.randn(100, 3) 
y_train = np.random.randint(0, 2, 100)

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def bce_loss(y_true, y_pred):
    y_pred = np.clip(y_pred, 1e-10, 1 - 1e-10)
    return -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))

# Train:
n, features = X_train.shape
w = np.random.randn(features)
b = 0.0
alpha = 0.1

print("Đào tạo thuật toán...")
for epoch in range(1, 201):
    # Forward Pass
    z = X_train @ w + b
    y_hat = sigmoid(z)
    loss = bce_loss(y_train, y_hat)
    
    # Backward Pass (Gradient)
    error = y_hat - y_train
    dw = (X_train.T @ error) / n
    db = np.mean(error)
    
    # Update Weights
    w -= alpha * dw
    b -= alpha * db
    
    if epoch % 50 == 0:
        print(f"Epoch {epoch} | Loss: {loss:.4f}")

# Độ chính xác cuối trên training
final_preds = (sigmoid(X_train @ w + b) >= 0.5).astype(int)
acc = np.mean(final_preds == y_train)
print(f"Accuracy trên Training set: {acc*100:.2f}%")

Đào tạo thuật toán...
Epoch 50 | Loss: 0.7024
Epoch 100 | Loss: 0.6666
Epoch 150 | Loss: 0.6634
Epoch 200 | Loss: 0.6629
Accuracy trên Training set: 59.00%


### Trưng dẫn tư duy cuối bài:
*   Nếu `loss` không giảm, 3 khả năng có thể xảy ra:
    1.  **Learning Rate** bị set sai. Nếu quá lớn -> Model bị overshoot diverge, nhún lố. Nếu nhỏ quá -> model kẹt ở bình địa và lâu xuống minimum.
    2.  Linh vị **Local Minima / Saddle point**: gradient $\approx 0$ chết đứng và không tối ưu thêm được trọng số tiếp.
    3.  Lỗi **Data Scale:** Model cần sử dụng data đã Normalize ra khoảng nhỏ (như `MinMaxScaler` hoặc `Z-score standardized`) - nếu không weights dễ bị gradient explode.

*   Chúng ta áp dụng Sigmoid layer nằm trên Regression để đảm bảo kết quả Output bị ép gọn về dải $[0, 1]$, từ đó biến bài toán Regress trở thành phân loại Classification xác suất.